### ISSUE TITLE
quantifier to measure fluorescence in area

### ISSUE THREAD

**Issue by gtfioreze** [Neural-Systems-at-UIO/nutil#125]
Hi,
Thanks for developing this tool! 
I am trying to use the quantifier operation to get the mean fluorescence in areas defined by the QuickNII software but not being very successful.
After registering coronal brain slices using QuickNII and getting segmented images with ilastik (here the masks are selecting the entire slice), I tried to run the quantifier with the outputs from those steps but I get the error: You need to specify at least one input file. Press the help button for instructions.
At the Segmentation folder I put the path to a directory with the .png files from ilastik (Object predictions from Pixel Classification and Object Classifications, with glasbery LUT). They are named i_001, i_002, i_003...
At the Brain atlas map folder I put the path to a directory with the .flat files from QuickNII. They are named i_001, i_002, i_003...
At the Anchored XML file I put the anchored file from QuickNII (.xml).

I am not sure I understand what this error mean and any help would be welcomed :)
Thank you!

**Comment by leuat** [comment]
Hi there!

Thanks for trying out QuickNII/Nutil etc!

If you're not using the recommended file name identifier (_s001,
_s002 etc), you need to specify a regular expression that matches
your file naming scheme. In your case (i_001 etc), you need to do
the following:

- click "show advanced settings"
- change the "unique ID format" from "_sXXX" to "user"
- Type in this regexp in the "other ID format" field : "i_[0-9]*"

"i_[0-9]*" is a regexp meaning that Nutil will look for files of the
format i_NNNNN , where NNN is a number. if you'd rather restrict the
search to files with *only* three numbers, you can instead type
"i_[0-9][0-9][0-9]".

Let me know if you have any problems!

regards

Nicolaas

> Hi,
> Thanks for developing this tool!
> I am trying to use the quantifier operation to get the mean
> fluorescence in areas defined by the QuickNII software but not being
> very successful.
> After registering coronal brain slices using QuickNII and getting
> segmented images with ilastik (here the masks are selecting the
> entire slice), I tried to run the quantifier with the outputs from
> those steps but I get the error: You need to specify at least one
> input file. Press the help button for instructions.
> At the Segmentation folder I put the path to a directory with the
> .png files from ilastik (Object predictions from Pixel
> Classification and Object Classifications, with glasbery LUT). They
> are named i_001, i_002, i_003...
> At the Brain atlas map folder I put the path to a directory with the
> .flat files from QuickNII. They are named i_001, i_002, i_003...
> At the Anchored XML file I put the anchored file from QuickNII
> (.xml).
>
> I am not sure I understand what this error mean and any help you
> would welcome :)
> Thank you!
>
>

**Comment by gtfioreze** [comment]
Hi,
Thanks for the reply. Problem was solved!
From the results one can get the count of objects per atlas area, but do you know if I can get the mean fluorescence? Or the fluorescence value for each pixel in the areas?
Thanks again

**Comment by sharoncy** [comment]
@gtfioreze It is not possible to calculate mean fluorescence with Nutil Quantifier. Quantifier takes atlas maps and segmentations generated from the original images as input, and calculates counts of objects and load per atlas region. The pixels that are counted are binary in nature - either ON or OFF, and are specified by the user in the Quantifer GUI based on a unique RGB colour code (so to count black pixels specify RGB 0,0,0). It is not possible to quantify multiple RGB colour codes in the same analysis.

**Comment by gtfioreze** [comment]
Ok! Thanks for the help!

**Comment by sharoncy** [comment]
@gtfioreze 
We discovered two bugs affecting the Quantifier reports in several older versions of Nutil, as the bugs were relatively serious we are informing all our users: 
Bug 1: 	Load output in the slice reports are incorrect for Nutil v0.4.0 – v0.5.0. The other results in the reports are correct. 
Bug 2: 	When using the mask feature: region pixels, region areas and loads in the reports are incorrect for Nutil v0.4.3 – v0.5.0. This bug does not affect analyses run without masks. 

The bugs are now fixed in Nutil v0.6.0 (stable), which is released on NITRC.org. As the bugs affected core Quantifier functionality, we have introduced more stringent quality assurance routines, with continuous integration (CI) and automatic validation based on an expanded collection of ground truth datasets. We will provide more information about this in a future Nutil release. Until then, please delete all affected analyses and rerun with the new version of Nutil. We are sorry for not picking up on this sooner! If you have questions, don't hesitate to contact me at s.c.yates@medisin.uio.no. 
Sharon
