### ISSUE TITLE
Unable to open Nutil.cmd on Windows 10 - missing .dlls

### ISSUE THREAD

**Issue by SadieRamon** [Neural-Systems-at-UIO/nutil#127]
When I try to run Nutil through the .cmd I get errors of missing .dlls and the program is unable to open. I tried to download these and add them to my System32, the error messages disappeared but I instead get "The application was unable to start correctly".

I am using Windows 10 x64. What can be the cause of this?

**Comment by SadieRamon** [comment]
Resolved the issue by installing Visual C++ Redistributable for Visual Studio 2015, version x64. Could possibly make it more explicit that it is a prerequisite, or somehow automatically install it if missing upon start of the application.

**Comment by leuat** [comment]
Hi there, thanks for mentioning this! I've had the same problem with my other application, but fixed the problem by adding a missing dll. Will do the same with Nutil, so you won't have to install MSVC redist!  Really nice to get this fixed.

**Comment by sharoncy** [comment]
Has the dll file been added to Nutil @leuat? If this has been fixed we should publish a new version on NITRC, just want to make sure it is done first!

**Comment by sharoncy** [comment]
@leuat ? what's the status here...

**Comment by sharoncy** [comment]
This has been fixed and published

**Comment by sharoncy** [comment]
@SadieRamon 
We discovered two bugs affecting the Quantifier reports in several older versions of Nutil, as these bugs are relatively serious we are informing all our users: 
Bug 1: 	Load output in the slice reports are incorrect for Nutil v0.4.0 – v0.5.0. The other results in the reports are correct. 
Bug 2: 	When using the mask feature: region pixels, region areas and loads in the reports are incorrect for Nutil v0.4.3 – v0.5.0. This bug does not affect analyses run without masks. 

The bugs are now fixed in Nutil v0.6.0 (stable), which is released on NITRC.org. As the bugs affected core Quantifier functionality, we have introduced more stringent quality assurance routines, with continuous integration (CI) and automatic validation based on an expanded collection of ground truth datasets. We will provide more information about this in a future Nutil release. Until then, please delete all affected analyses and rerun with the new version of Nutil. We are sorry for not picking up on this sooner! If you have questions, don't hesitate to contact me at s.c.yates@medisin.uio.no. 
Sharon
