### ISSUE TITLE
Question Regarding Masks

### ISSUE THREAD

**Issue by howardli123** [Neural-Systems-at-UIO/nutil#137]
Hello,

Thank you for developing this software! In the Quantifier function of Nutil, I'm having a little bit of trouble understanding the function of masks. For my purposes, I need Nutil to give counts for all brain regions in the coronal sections I have inputted. Would a mask be necessary in this case? Are masks used to designate specific regions that are the inclusion area?

Furthermore, oftentimes we get background staining during IHC that we usually exclude. Is there any way in the QUINT workflow to exclude particular signals that are artifacts so that they are not included in the final counts? 

Thank you so much again!

**Comment by sharoncy** [comment]
A mask is not necessary in your case. Nutil quantifies objects per reference atlas region based on the atlas maps provided. The mask feature allows you to define an inclusion area that is applied on top of the reference atlas region definitions. For example, to get output for all the reference atlas regions in the left hemisphere only, a mask that differentiates the two hemispheres could be applied.

To remove artifacts in Nutil you can set a min and max object size. This is good for removing
artifacts that are significantly smaller or larger than your objects of interest. If this doesn't apply in your case, you will have to remove the artifacts in the segmentation step. The object classification workflow in ilastik is useful in some cases (see the ilastik user manual included in the Nutil package). Alternatively, NIH ImageJ or some other image analysis software may be used to remove artifacts.

Let me know if you need any more input.

**Comment by howardli123** [comment]
That makes perfect sense, thank you so much!

**Comment by sharoncy** [comment]
@howardli123 
We have discovered two bugs affecting the Quantifier reports in several older versions of Nutil, as the bugs are relatively serious we are informing all our users: 
Bug 1: 	Load output in the slice reports are incorrect for Nutil v0.4.0 – v0.5.0. The other results in the reports are correct. 
Bug 2: 	When using the mask feature: region pixels, region areas and loads in the reports are incorrect for Nutil v0.4.3 – v0.5.0. This bug does not affect analyses run without masks. 

The bugs are now fixed in Nutil v0.6.0 (stable), which is released on NITRC.org. As the bugs affected core Quantifier functionality, we have introduced more stringent quality assurance routines, with continuous integration (CI) and automatic validation based on an expanded collection of ground truth datasets. We will provide more information about this in a future Nutil release. Until then, please delete all affected analyses and rerun with the new version of Nutil. We are sorry for not picking up on this sooner! If you have questions, don't hesitate to contact me at s.c.yates@medisin.uio.no. 
Sharon
