### ISSUE TITLE
Problem running ilastik with tiletiff

### ISSUE THREAD

**Issue by GxHam** [Neural-Systems-at-UIO/nutil#170]
Hi,

@sharoncy thanks for the comprehensive ilastik manual included in nutil! Following the manual for ilastik, I encountered issues when trying to convert tiledTIFF files to HDF5 as recommended on page 4-5. 

![image](https://user-images.githubusercontent.com/53009065/100966667-6c03ee80-3568-11eb-90c6-3e51faa06042.png)

The tiledTIFFs obtained from nutil also fail to load in ilastik.

What image format should be used for this step? Would it be possible to include a HDF5 conversion in Nutil as well? I understand conversion can be done using FIJI, but would like to clarify what might be the best approach.

**Comment by sharoncy** [comment]
I don't think ilastik supports tiled tiffs, see: https://www.ilastik.org/documentation/basics/dataselection. I always work with PNG images in ilastik, but you can check out the list for compatible formats. The tiled tiffs generated with "Transform" are intended for other purposes. To generate PNGs from tiled Tiffs, you can use the thumbnail feature in Transform. Select "advanced settings", select "only create thumbnails", and select an appropriate resize factor (see the help button next to "thumbnail size" for more info). If the original images are in PNG or JPEG format, use the "Resize" function in Nutil. Depending on the size of your images, it may also be possible to resize/convert to PNG in Fiji or Adobe Photoshop, etc. I hope you find a solution, let us know if you need more help!

Thanks for pointing out this issue, it isn't well described in the user manual. I will make sure to update this for the next release.

**Comment by GxHam** [comment]
Hi Sharon,

Thank you so much for the clarification! I converted my images to PNG using the thumbnail option, and am able to run the images through Pixel classification, followed by object classification. I would like to further clarify on 4 more items though: 

1) what would be a recommended appropriate resize factor, and how do I go about considering that? I resized my images with a scale of 0.5, but the prediction map output still seems pretty slow.

2) when you mention "export simple_segmentation in 8-bit PNG" on page 7, do you mean clicking on `Export All`? or right click followed by export?

3) Do I actually need to export the prediction probabilities & simple_segmentation in the Prediction export tab, or can I do all of it in the Batch Processing applet?

4) Do I need both simple_segmentation and prediction probabilities for all images before running object classification?

I do understand that this is more an issue related to ilastik, but would like your opinion given your experience :) Thank you so much for helping!! Loving the pipeline so far :)

**Comment by sharoncy** [comment]
Question 1: The best resize factor is dependent on the original size of your images and the size of the features that you wish to extract. Ideally, you should resize so that the objects of interest (for example, cells) fall well within a 10 x 10 pixel window. The ilastik algorithm operates on a scale up to 10 sigma (10 x 10 pixels), meaning it can identify the edges of objects within this scale. I have worked with a resize factor of 0.2 - 0-.1 in the past. I always try to work just with pixel classification if possible, as the object classification workflow complicates things. However, the object classification workflow is very useful in some cases - to differentiate the objects of interest from other objects (e.g artifacts). The classical example is cells and edge staining, which both have an edge that falls within a 10x10 pixel window and so are extracted by pixel classification, but have a different shape and so are easy to differentiate with object classification (round versus long and thin). 

Question 2/3: You can export everything in the Batch processing applet. Just select the right settings in the prediction export tab, and do the export in the batch processing applet. So, select simple segmentations in 8-bit PNG and then batch export. And then select prediction probabilities in HDF5 and batch export. 

Question 4: The simple_segmentations are needed to inspect and validate the output of the pixel classification, but are not technically necessary for object classification (it is a good idea to inspect them though!). The prediction probabilities are necessary to run the object classification.

**Comment by sharoncy** [comment]
@GxHam 
We discovered two bugs affecting the Quantifier reports in several older versions of Nutil: 
Bug 1: 	Load output in the slice reports are incorrect for Nutil v0.4.0 – v0.5.0. The other results in the reports are correct. 
Bug 2: 	When using the mask feature: region pixels, region areas and loads in the reports are incorrect for Nutil v0.4.3 – v0.5.0. This bug does not affect analyses run without masks. 

The bugs are now fixed in Nutil v0.6.0 (stable), which is released on NITRC.org. As the bugs affected core Quantifier functionality, we have introduced more stringent quality assurance routines, with continuous integration (CI) and automatic validation based on an expanded collection of ground truth datasets. We will provide more information about this in a future Nutil release. Until then, please delete all affected analyses and rerun with the new version of Nutil. We are sorry for not picking up on this sooner! If you have questions, don't hesitate to contact me at s.c.yates@medisin.uio.no.
