### ISSUE TITLE
Cell quantification in reference atlas

### ISSUE THREAD

**Issue by AndreaLopes** [Neural-Systems-at-UIO/nutil#190]
Hello everyone!

First of all, thank you for developing such useful tool!
I have a question regarding the _Quantifier_ feature of Nutil. From what I understood, cell quantification can be performed by using reference atlas such as the Allen Mouse Brain reference atlas or the Waxholm Space Atlas of the Sprague Dawley rat brain.
I was wondering whether it would be possible to use a reference atlas we have generated in the lab, rather than using the ones of the Allen brain atlas? The idea would be then to perform cell quantification within each annotated region in our atlas and have a better understanding of the cell distribution in the various areas of the brain.

Thank you very much in advance!

**Comment by sharoncy** [comment]
Thank you for your request. 

Support is implemented in Nutil v0.6.0 for other reference atlases, but we have not yet implemented support for this in QuickNII, which is required to generate the atlas maps and anchoring file that are needed for Quantifier to work. It would therefore require some work on our part. We are considering establishing a service for this sort of request, so if it is something you'd like to pursue further, please put in an official request through ebrains support https://ebrains.eu/support (alternatively, email: support@ebrains.eu) with some more information about your reference atlas, whether the atlas is publicly shared, or whether you are open to sharing it publicly (this isn't a requirement for us to provide help - but is of interest to us). Great if you include a reference to QUINT and Maja Puchades in the request so that the frontline staff can more easily direct it to us. 

Best wishes, Sharon Yates.

**Comment by Majpuc** [comment]
This ticket will be closed now (03.09.2021) Please open a new one if you have further questions.
