### ISSUE TITLE
WHSv3 atlas region error in Quantifier output

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/nutil#215]
Error from an user:

I tried to test run the QUINT-workflow with the WHS v3-atlas and some of the brain areas were wrongly labelled.

As you can see in the attached image, e. g. "corpus callosum and associated subcortical white matter" is labelled as "olfactory bulb", "neocortex" as "pyramidal decussation" and "hypothalamic region" as "brainstem".

**Comment by Majpuc** [comment]
What is puzzling is that I cannot detect any objects from the segmentation file but the atlas output has altered colors!
![image](https://user-images.githubusercontent.com/46992863/125410312-0f4d9980-e3bd-11eb-9dd2-462bf083c420.png)

**Comment by sharoncy** [comment]
@Majpuc is this also reported by Wissewald or another user? The altered atlas colours is something that happens if there is a discrepancy in the atlas versions: for example, different version used for QuickNII and Nutil. Additionally, it is possible that the colour selected for extraction doesn't match the object colours in the segmentation, hence no objects extracted. 

It is impossible to investigate without example files so please ask the user to send a copy of an atlas map, a matching segmentation, the xml/json and the Nut file. @Majpuc @leuat  @Tevemadar In time we should try to find a solution for the versioning issue as this keeps repeating.

**Comment by sharoncy** [comment]
This has been resolved. Sharon 28.07.21.
