### ISSUE TITLE
How to get brain areas of bregma-coordinates of the Nutil Quantifier output file

### ISSUE THREAD

**Issue by Wissewald** [Neural-Systems-at-UIO/nutil#219]
Dear Nutil-community,

I was trying out the QUINT-workflow and, so far, it works pretty fine.
I registered my test-slice in the WHSRat-v3 with QuickNII, did some fine alignment with VisuAlign, ran the Nutil Quantifier analysis and (thanks to Sharon) have got the bregma-coordinates for the coornidates of my objects in the json-file, in the output-folder of Nutil Quantifier.

Now, since I need a more detailed segmentation than the WHSRat-v3, I was trying to get the brain areas of bregma coordinates of my objects from e.g. Paxinos/Watson-atlas or Sigma-atlas
https://www.nature.com/articles/s41467-019-13575-7 
but I couldn't find a way to do so.

The Paxinos/Watson-atlas was even spacially registered to the WHS-atlas 
https://search.kg.ebrains.eu/instances/Dataset/97e10f88-5c64-47fe-93a0-7cc3262a8bcd 
but I cannot get it due to copyright issues. We have this atlas (7th edition) as a print version in the lab. Maybe someone knows if it's possible to buy it registered into the WHS-atlas.
Or, if someone could give me a hint how to get brain areas from bregma-coordinates, at least with some cortical and subcortical areas (ideally as detailed as in Paxinos/Watson), I'd be grateful for any support.

**Comment by Majpuc** [comment]
As you've found out, the The Paxinos/Watson-atlas was  spatially registered to the WHS v3 and the coornate xml file is freely accessible through the EBRAINS website.
https://search.kg.ebrains.eu/instances/Dataset/97e10f88-5c64-47fe-93a0-7cc3262a8bcd
This could allow you to compare coordinates points between your dataset and the Paxinos/Watson atlas. Have a look at the data descriptor file for a description on how this xml file can be used.
However, Nutil Quantifier relies on the brain atlas regions label file and flat files from QuickNII/VisuAlign in order to assign segmented objects to the brain regions. This will not be possible for the Paxinos/Watson atlas, as we don't have a label file.

We don't support (yet) a coordinate transformation script, but this is in our pipeline.

I am afraid that the best solution would be to wait for the version 4 of the Waxholm atlas for cortical regions delineations. As already mentioned this version is expected to be published towards the end of this month.

**Comment by Majpuc** [comment]
This issue will be closed (03.09.2021). Please open a new ticket if you have further questions :)
