### ISSUE TITLE
Nutil Quantifier v0.6.0 - Object count N/A

### ISSUE THREAD

**Issue by anhknguyen96** [Neural-Systems-at-UIO/nutil#226]
Hi, I'm using the Nutil Quantifier as part of the QUINT workflow. Attached is the segmentation result from ilatsik, output image from nutil, screenshot of data from refatlasregion file, screenshot of data from customregions file. I'm trying to figure out why there's no object count.
Many thanks.

<img width="486" alt="refatlas" src="https://user-images.githubusercontent.com/30437493/132264143-4a31fd78-8241-4d03-9174-60b358dcc84e.png">

<img width="613" alt="segmentation" src="https://user-images.githubusercontent.com/30437493/132264140-f33dbe4a-de36-4344-9629-8a1fc5a5d7ad.png">
<img width="541" alt="custommaps" src="https://user-images.githubusercontent.com/30437493/132264141-e4f3fa1c-0206-46b5-b3f9-8d8b3ad65722.png">

<img width="624" alt="outputnutil" src="https://user-images.githubusercontent.com/30437493/132264139-122a90b1-2ed7-4704-8cce-202804369c29.png">

**Comment by Majpuc** [comment]
Dear Anh,

Thank you for your request. Could you please send an email to support@ebrains.eu as we have to regroup our support on the Ebrains platform. In order to troubleshoot your dataset, could you please attach with the email, the nut file you saved, the xml or json file with anchoring data and a sample of your QuickNII raw images and corresponding ilastik segmentation images as well?
Thank you for your patience !
Best, Maja

**Comment by Majpuc** [comment]
Issue resolved 09.09.2021

**Comment by FanLihai** [comment]
Hi, I had a similar problem when I was using Nutil0.8.0. Object count N/A. Can you tell me how did you solve this problem? 
Thanks a lot.

**Comment by FanLihai** [comment]
Thank you sharon! The problem has been solved.
