### ISSUE TITLE
Add regions outside the allen atlas

### ISSUE THREAD

**Issue by namercer** [Neural-Systems-at-UIO/nutil#240]
Hi,

The Nutil quantifier runs well on the regions inside the Allen CCF but I am trying to quantify the entire brainstem, including the region ~2 mm poster to the edge of the Allen CCF. Is there a way to extend the Allen object files for the most posterior nuclei (e.g. spinal trigeminal nucleus caudalis, nucleus of the solitary tract, medullary reticular formation)? I was hoping to do this through the custom regions, but it looks like that only allows for making custom groups of predefined Allen regions.

**Comment by leuat** [comment]
Hm, an interesting question indeed! 

Nutil is quite agnostic when it quantifies the regions. Brain atlas region ID numbers are extracted from the .flat files, and are matched with the corresponding atlas (allen/waxholm etc) label file. In other words: Nutil only depends on the lookup .flat files and the corresponding atlas label file. 

In order to *extend*  this, you have two options:

a) design an extended Allen atlas (3d data + label files) and go through exporting with quicknii -> nutil (all with the new atlas).. which is quite a daunting task =)

b) since Nutil is data agnostic, it could be possible to manually "ID paint" the regions you are interested in in the flat files (say, with a custom label ID of 65000) and then add "id 65000" to a "custom" label file that nutil uses to extract the data. While part 2 of this would be straightforward to implement (just add support for a custom label file), there are yet *no ways* to visually modify the .flat files, as these aren't regular image files at all. In any case this is probably something that would have to be implemented in QuickNII/WebNII (defining "custom areas" with custom IDs) before exporting the flat files, and would require some extensive planning. 

This really isn't something that we are able to prioritise right now, but it is definitely something for the future - 1) adding support for custom labels and 2) being able to modify .flat files in some way.

**Comment by Majpuc** [comment]
@sharoncy As this question was asked now by another user, can you add this information to the FAQ in Readthedocs?

**Comment by sharoncy** [comment]
@Majpuc did you mean the part about Nutil not supporting regions that fall outside of the reference atlases? Or how to quantify objects in ROI without the use of QUINT? The second part seems outside the scope of the QUINT Read the Doc, but if it would reduce confusion/unnecessary questions, I could add a sentence or two about it.

**Comment by sharoncy** [comment]
I have added info. issue closed 19.01.22.
