### ISSUE TITLE
Unknown issue with running dataset in Quantifier

### ISSUE THREAD

**Issue by ingvildeb** [Neural-Systems-at-UIO/nutil#267]
Hi! I have a dataset that just won't run in Quantifier. I have many files with similar paths and using the same (custom) atlas that have run perfectly and am not able to understand why this one doesn't.

![image](https://user-images.githubusercontent.com/28010291/186662853-a34da1cc-305c-4d65-bc82-ef0e82d2b732.png)

The .nut file is located here: Y:\2021_Bjerke_CalciMap-project\Analyses\Nutil\P35\Calbindin and all the paths are on the server. I would greatly appreciate help investigating this.

**Comment by sharoncy** [comment]
Ingvild and I looked at this yesterday. The reason it didn't run is because there was a FLAT file missing. The other warnings came up because there were sections in the .json that had not been anchored since they fell outside of the reference atlas: the warning messages did not give this info so it was hard to figure out. Removing these sections from the .json fixed the problem.This is not a use case we have come across before, which is why the warning messages didn't describe the problem sufficiently. Consider revising the warning messages.

**Comment by sharoncy** [comment]
I will add a new issue to review/revise the warning messages. This issue can be closed. 26.08.22.

**Comment by Majpuc** [comment]
Very good. Is the reason for the missing flat file identified? faulty export?

**Comment by ingvildeb** [comment]
No, it was a section that had been excluded during anchoring (image removed from QuickNII and VisuAlign files) but there was still a segmentation image for it, so just a mistake on my side.
