### ISSUE TITLE
How to get one WHS-v4 coordinate per object instead of every pixel in Nutil Quantifier?

### ISSUE THREAD

**Issue by Wissewald** [Neural-Systems-at-UIO/nutil#284]
In the Nutil Quantifier output, I'd like to get one coordinate per object instead of one coordinate per pixel in the .json-file, to be able to do population analysis.
 
I found the line
 
coordinate_single_point; 1; ;Output single central point instead of all points; list; Yes, No; No
 
in
 
https://github.com/Neural-Systems-at-UIO/nutil/blob/master/Resources/text/quantifier.txt
 
So it must be somehow possible to change it to "Yes", but adding "coordinate_single_point = Yes" the .nut-file doesn't work 
(Warning: could not find parameter "coordinate_single_point").
 
Is there a way to change this setting or maybe a workaround to get one WHS-v4 coordinate per object in the .json-file?

**Comment by leuat** [comment]
Hi there! Yeah this is a new feature that isn't fully tested yet and hasn't been released.. but we decided today to start putting out nightly (so-called unstable versions) so users will be able to try out new features. Will see if I can get it up and running during this weekend!

regards

Nicolaas

**Comment by Wissewald** [comment]
Thanks a lot for the fast reply! It's not essential for my project but a very nice to have for point cloud density analysis and maybe also further segmentation of the WHS-v4 atlas.

**Comment by Wissewald** [comment]
Actually it doesn't necessarily have to be the center of the object, for my needs it would be enough to have the coordinates of one (but only one) pixel per object.

**Comment by sharoncy** [comment]
Hi. Our developer has released a version with your requested feature (go to "Releases" here https://github.com/Neural-Systems-at-UIO/nutil, release v0.8.7 (pre-release). In Nutil Quantifier, use the "output single central point instead of points" feature. But it is important to keep in mind that this is a pre-release! It has not been through proper testing procedures, which means that there could be errors in the reports. It is therefore important to do your own validation if you intent to use these results in your research. I suggest that you use this version only to generate the coordinates, and that you use the stable version (v0.8.0) for anything else (for example, for the RefAtlasRegion and CustomRegion reports). And please let us know if you spot errors /inconsistencies. Sharon

**Comment by Wissewald** [comment]
Thanks a lot for the fast implementation. It seems to work pretty well, I get only one triplet per object and the positions seem to correct (uploaded in MeshView and plotted in MATLAB).
In case I'll find some errors, I will report it here.
