### ISSUE TITLE
issues with transform

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/nutil#299]
06/06/2023
Hi,
I tried to perform transform operations but they failed. Typically, the transformation is run on the same number of files than the number of chosen cores but then the sw crashes with no error message. I am using the feature "from Excel file" in order to rename with a flipping of -1 in scale Y.
I tried it on v0.0.7; v0.0.8 and v.0.8.8 and with several datasets. They all had the same behavior although the same files and same Nutil versions have worked before. I cannot see in the cmd window what the message is.
Could you see if you reproduce the error @sharoncy ?

**Comment by sharoncy** [comment]
Hi Maja. In my experience since the upgrade to the new IT system at UiO, Nutil has been unable to run on files located on the Nesys server. The connection always cuts out before Nutil can finish processing, which crashes the program. Nutil still works fine if you save the files locally first. I assume you tried to apply Transform to files stored on the server? This obviously makes it difficult to work with Nutil in practise, not sure if there is a solution...

**Comment by Majpuc** [comment]
Hi Sharon, Thank you for reminding me about this! Maybe you could bring this op in the documentation under "technical information"?

**Comment by Majpuc** [comment]
implemented
