### ISSUE TITLE
PLEASE HELP : Count of Pixels 0 issue

### ISSUE THREAD

**Issue by YANGBYUNGJUN201** [Neural-Systems-at-UIO/nutil#311]
![Screenshot 2023-11-08 183011](https://github.com/Neural-Systems-at-UIO/nutil/assets/149761829/1e229512-0886-454d-afa3-28b4588b5c62)
![Screenshot 2023-11-08 183119](https://github.com/Neural-Systems-at-UIO/nutil/assets/149761829/51671db4-bcef-42c3-9924-45c6d3add80e)

I'm trying to use quantifier but count of pixels 0 keeps come up as you can see on the picture
Anyone please help

**Comment by Majpuc** [comment]
Dear Jun,

Thank you for using our tools! This count at 0 could be caused by a range of different things. it could be for example that you have the object splitting turned on (see our FAQ here: https://nutil.readthedocs.io/en/latest/FAQ.html). It could be some other reasons as well, like a mismatch between the file names of the segmentations and the atlas registrations. For us to troubleshoot, we would need some raw sample images, images of your segmentation, the registration file (xml or Json), your Nutil quantifier nut file. I see that you opened a support ticket already on EBRAINS, that is fantastic. Can you send the files to the same email? Thanks!

**Comment by YANGBYUNGJUN201** [comment]
Thank you for your rapid response Maja! I couldn't expect to receive your
mail ike this lightwave speed.
I have tried to turn off the object splitting, but it didn't work
unfortunately. Like you said, I'm now sending you my raw sample images,
images of segmentation, regisration file, Nutil quantifier nut file. Hope
we can find a way to solve this problem together.

segmentation file : FLAT, anchoring file : xml, segmentation file : png,
raw sample image : jpg

2023년 11월 8일 (수) 오후 7:36, Maja ***@***.***>님이 작성:

**Comment by Majpuc** [comment]
Hi  Byung Jun,
Nice if you could send the files as attachment in reply of the support ticket email Ticket# 4821750.
Thanks!

Best, Maja
