### ISSUE TITLE
Y Axis in Plots

### ISSUE THREAD

**Issue by Noy987** [Neural-Systems-at-UIO/nutil#317]
What is the meaning of the title "Load" in the Y axis in these plots?
Thanks!

![image](https://github.com/Neural-Systems-at-UIO/nutil/assets/154227249/92624766-f1f4-47a4-a7c4-1884855817a9)
![image](https://github.com/Neural-Systems-at-UIO/nutil/assets/154227249/9694e0f6-5d2b-4c48-b7ab-def40f5e53fc)

**Comment by sharoncy** [comment]
The load refers to the area fraction (regional coverage). So a load of 0.250 means that 25% of the region is covered by labelling. Let me know if you have any more questions.

**Comment by Noy987** [comment]
Thanks! 
Are there plots for object count?
Is there also a bug in the object count in Excel? Because mine states "N/A" in the corresponding column.

![image](https://github.com/Neural-Systems-at-UIO/nutil/assets/154227249/2ed30e31-043d-404f-8f36-048d4109b796)

**Comment by sharoncy** [comment]
Hi,
We don't currently have plots for object counts. To get object counts, switch the object splitting "off". With this setting, each segmented object is registered to one region only, giving correct "object counts" per atlas-region. However, it can invalidate the regional load measurements, especially if the objects are large. When object splitting is "on" it means each segmented object pixel is registered individually (in other words, objects that overlap one or more atlas-regions will be split into parts and registered to their correct regions). This gives exact regional load measurements but invalidates the object counts (which is why N/A is there). You can read more here https://nutil.readthedocs.io/en/latest/QuantifierOS.html. 

Let me know if this doesn't fix the problem and I'll look into it further. 
Sharon
