### ISSUE TITLE
Running on a Mac

### ISSUE THREAD

**Issue by Orowa** [Neural-Systems-at-UIO/nutil#99]
HI there, the instructions mention that Nutil can be run on all operating systems; so far I can only see a .cmd file to execute on Windows. Is there some alternate way to run on a Mac? Or is this support that is being developed?

**Comment by leuat** [comment]
Hi there! We haven't actually published any version for macos yet, since a) I don't have a mac and b) nobody have asked for it. So, congratulations on being the first one! In any case, I'll see if I can manage to set up a VM and get macos installed so I can compile up a version for this OS as well. Don't know exactly when this will happen, though.

**Comment by Orowa** [comment]
Thank you! I'll be able to use that to run my process so eagerly anticipating :)

**Comment by leuat** [comment]
We'll ask Dmitri on friday (June 5th) about borrowing his Mac!

**Comment by sharoncy** [comment]
The image picker on Mac doesn't work as it should. Plan is to instead implement field for manually entering RGB colour code. This should be explained in the help text.

**Comment by sharoncy** [comment]
I have updated the help text for Windows and Mac computers.

**Comment by leuat** [comment]
Before doing a full release, I've put out a macos version here : https://www.irio.co.uk/L/nutil.tar.gz . Orowa, would you be able to test this version and verify that it works?

**Comment by sharoncy** [comment]
We should test this ourselves on another Mac so we can publish the Mac version on NITRC.

**Comment by Rodrigogq13** [comment]
Hi, I was wondering if there has been an update with the Mac version of Nutil? I am very interested in using it. Thanks in advance!

**Comment by leuat** [comment]
@Rodrigogq13 if you check out the reply from August 5, you'll find a link to an early MacOS version. I'll update it with an official link a bit later, and we'll also be having Apple M1 support in the future.

Nicolaas

**Comment by Rodrigogq13** [comment]
Hi,
Thank you very much!
I tried the version on August 5, but it does not seem to be working. It says it cannot be open because of a problem and to check it works with this version of MacOS. I am using 11.1 but it said the same with an older version

**Comment by sharoncy** [comment]
@Orowa 
We discovered two bugs affecting the Quantifier reports in several older versions of Nutil: 
Bug 1: 	Load output in the slice reports are incorrect for Nutil v0.4.0 – v0.5.0. The other results in the reports are correct. 
Bug 2: 	When using the mask feature: region pixels, region areas and loads in the reports are incorrect for Nutil v0.4.3 – v0.5.0. This bug does not affect analyses run without masks. 

The bugs are now fixed in Nutil_win_v0.6.0 (stable), which is released on NITRC.org. As the bugs affected core Quantifier functionality, we have introduced more stringent quality assurance routines, with continuous integration (CI) and automatic validation based on an expanded collection of ground truth datasets. We will provide more information about this in a future Nutil release. Until then, please delete all affected analyses and rerun with the new version of Nutil. We are sorry for not picking up on this sooner! We haven't released a MacOs version yet, but I'll let you know if this changes. If you have questions, don't hesitate to contact me at s.c.yates@medisin.uio.no. 
Sharon

**Comment by sharoncy** [comment]
@Rodrigogq13 Please read the comment above about the Nutil bugs, I meant to copy you in. You can download a stable windows version at NITRC.org

**Comment by matteopa** [comment]
Sorry for disturbing, when the mac version will be available i'll find it here https://www.nitrc.org/projects/nutil/ right?
Thanks for your work!

**Comment by leuat** [comment]
Hi @matteopa ! I just fixed up a problem with some of the libraries, compiled a new macos version and tested it on my apple M1 mac  - you can download the latest version from https://www.irio.co.uk/div/nutil_mac_tar.gz. Let me know if you encounter any problems with it!

**Comment by matteopa** [comment]
Perfect, I also have an m1 mac. Thank you and have a nice day!

**Comment by Majpuc** [comment]
We close this issue now, on 25.08.2021. If you still have issues, please open a new ticket.
